### ISSUE TITLE
TimeStamp issue

### ISSUE THREAD

**Issue by mokbul469** [shahriar-shojib/nagad-payment-gateway#10]
I think there have a problem in src/index
getTimeStamp() month if October  should return 10 but it's return 9. Please fix it.

**Comment by shahriar-shojib** [comment]
i will try to fix it soon.

if you have a quick fix for it, feel free to open a PR. 🤠

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: mokbul469 ***@***.***>
Sent: Friday, October 14, 2022 10:01:02 PM
To: shahriar-shojib/nagad-payment-gateway ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [shahriar-shojib/nagad-payment-gateway] TimeStamp issue (Issue #10)


I think there have a problem in src/index
getTimeStamp() month if October should return 10 but it's return 9. Please fix it.

**Comment by shahriar-shojib** [comment]
fixed in [v2.0.2](https://github.com/shahriar-shojib/nagad-payment-gateway/releases/tag/v2.0.2)
