### ISSUE TITLE
TypeError: NagadGateway is not a constructor

### ISSUE THREAD

**Issue by khokonm** [shahriar-shojib/nagad-payment-gateway#12]
I get this error when I tried to implement the project as per your instruction on the readme.

**Comment by shahriar-shojib** [comment]
I will try to replicate this issue locally, I suspect this is due to incorrect exports in package.json

**Comment by khokonm** [comment]
Thank you. I had to extract the whole package function by function for this issue 😆.
I eventually got the job done, but I hope solving this issue will help future devs

**Comment by shahriar-shojib** [comment]
please use this style of import it should be fixed now
```
const { NagadGateway } = require('nagad-payment-gateway');
```
